# Generated by Django 4.1.7 on 2023-03-28 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0003_authordetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_quotes.author'),
        ),
    ]
